- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml
    

- name: Create Job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{DIR}}/{{COMPONENT}}"
    url: http://172.31.83.253:8080
    user: admin
    password: "{{jenkins_password}}"